### ISSUE TITLE
[v2.1+1.19.2] Mod not working with minecraft-1.19.3, only vanilla stats screen comes up.

### ISSUE THREAD

**Issue by Litos926** [TheCSDev/mc-better-stats#26]
Description:
Pressing the statistics button only brings up the vanilla stats screen.
This happens even if the mod is the only one installed.

I am using the fabric loader version 0.14.11 for Minecraft 1.19.3.

**Comment by TheCSDev** [comment]
Yup, this appears to only be the case on 1.19.3. I have quickly removed 1.19.3 from the list of supported versions on both CurseForge and Modrinth so it doesn't end up confusing even more people. Thanks a lot for reporting this bug.

I have not yet investigated, but I will right now. For now I believe Mojang might've changed the translation key for the "Statistics" text, thus "confusing" the mod and making it not work.
*Cuz who'd've guessed... Mojang at it again, making mod-breaking changes to the game, as usual* (sorry about that, it does get annoying when it happens tho).

**Comment by TheCSDev** [comment]
After further testing, it seems the translation keys are okay. So in other words, something else is causing this. I will keep looking for now.

**Comment by TheCSDev** [comment]
Yeah, it appears Minecraft's code (and/or the mappings) changed quite a bit in 1.19.3, making this mod not work at all in 1.19.3. Honestly I have no idea how this mod doesn't just straight up crash the game. I will port to 1.19.3 later today, as it is getting very late for me now (past midnight). Thanks again for the report and sorry for the inconvenience. Have a great day as well.

**Comment by TheCSDev** [comment]
Hello again. It appears Mojang has almost completely rewritten the `GameMenuScreen` and the `ItemGroup` system. No wonder why this mod stopped working. I have identified the issue tho, and am working on resolving it.

Honestly I don't like how they decided it would be a great idea to start making large changes to the game's code in "patch" releases now (`1.x.x`), instead of only "minor" releases (`1.x`). Because of this, I can no longer release a mod for let's say `1.19.x` and then not worry about it for the next year, instead I have to worry about every `.x` update, which complicates things even more. Because of this, this mod also broke in the past for `1.19.2`, and I had to deal with that as well.

Anyways, now I have to figure out how to fix the `ItemGroup` handling. Once I am done with that, the mod will be ready for 1.19.3.

**Comment by TheCSDev** [comment]
Done. The issue has finally been dealt with and resolved. I did have to make quite some changes to a bunch of stuff in a way, but it worked out in the end. It will take a while for me to fully play-test and then release the 1.19.3 patch tho. Thanks again for the report and have a great day.
